version: "3.8"
services:
  cryptobot:
    build: .
    container_name: cryptobot
    image: cryptofreealertsbot/alertbot:1.0
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis:alpine3.17
    volumes:
      - redis_data:/data
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  redis_data: {}